# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3852, 1938)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_search = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_search.setGeometry(QtCore.QRect(1170, 1540, 700, 200))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton_search.setFont(font)
        self.pushButton_search.setObjectName("pushButton_search")
        self.pushButton_load = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_load.setGeometry(QtCore.QRect(50, 1540, 800, 200))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setObjectName("pushButton_load")
        self.img_widget = QtWidgets.QWidget(self.centralwidget)
        self.img_widget.setGeometry(QtCore.QRect(20, 20, 1920, 1440))
        self.img_widget.setObjectName("img_widget")
        self.textEdit_title = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_title.setGeometry(QtCore.QRect(1990, 120, 1441, 151))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(18)
        self.textEdit_title.setFont(font)
        self.textEdit_title.setObjectName("textEdit_title")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(1990, 20, 231, 81))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(18)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_processes = QtWidgets.QLabel(self.centralwidget)
        self.label_processes.setGeometry(QtCore.QRect(2760, 360, 321, 81))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(18)
        self.label_processes.setFont(font)
        self.label_processes.setObjectName("label_processes")
        self.label_ingredients = QtWidgets.QLabel(self.centralwidget)
        self.label_ingredients.setGeometry(QtCore.QRect(1990, 360, 411, 71))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(18)
        self.label_ingredients.setFont(font)
        self.label_ingredients.setObjectName("label_ingredients")
        self.textEdit_ingredients = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_ingredients.setGeometry(QtCore.QRect(1980, 450, 751, 1381))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        self.textEdit_ingredients.setFont(font)
        self.textEdit_ingredients.setObjectName("textEdit_ingredients")
        self.textEdit_processes = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_processes.setGeometry(QtCore.QRect(2760, 450, 1071, 1381))
        font = QtGui.QFont()
        font.setFamily("メイリオ")
        font.setPointSize(16)
        self.textEdit_processes.setFont(font)
        self.textEdit_processes.setObjectName("textEdit_processes")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3852, 47))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_load.clicked.connect(MainWindow.click_load)
        self.pushButton_search.clicked.connect(MainWindow.click_search)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_search.setText(_translate("MainWindow", "Recipe search"))
        self.pushButton_load.setText(_translate("MainWindow", "Image acquisition"))
        self.label_title.setText(_translate("MainWindow", "Title"))
        self.label_processes.setText(_translate("MainWindow", "Processes"))
        self.label_ingredients.setText(_translate("MainWindow", "Ingredients"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))


